site_name: Learn Python
theme: readthedocs
docs_dir: src
site_dir: generated

extra_css:
    - css/extra.css

nav:
    - Home: index.md
    - Mkdocs:
        - Usage: ./mkdocs/usage.md
    - Leetcode:
        - Data Structure: ./leetcode/data-structure.md
        - Problems: ./leetcode/problems.md