site_name: SDE Learnings

theme:
    name: material
    palette:
        primary: light green
        accent: deep orange
    logo: assets/logo.png
    favicon: assets/logo.png

docs_dir: src
site_dir: generated

extra_css:
    - css/extra.css
plugins:
    - search
    - awesome-pages
nav:
    - Home: index.md
    - ...